<a href="https://colab.research.google.com/github/Divyashree-iyer/Machine-Learning/blob/master/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [31]:
dataset = pd.read_csv('Data.csv')
#country, age, salary (except last)
X = dataset.iloc[:, :-1].values
#purchased (only last)
y = dataset.iloc[:, -1].values

In [8]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

## Taking care of missing data

In [32]:
#replacing missing data with mean of the column
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#calculate mean of age and salary
imputer.fit(X[:, 1:3])
#makes replacement of np.nan with mean
X[:, 1:3] = imputer.transform(X[:, 1:3])


In [ ]:
print(X)

## Encoding categorical data

### Encoding the Independent Variable

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#here france, germany and spain are independent i.e. no country 
#is above other hence we use one hot encoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

### Encoding the Dependent Variable

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#replace yes with 1 and no with 0
y = le.fit_transform(y)

In [43]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [49]:
from sklearn.model_selection import train_test_split
#split data - get training and test set
#20% test and 80% training
#random attr so that all get same result (ceed variable)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [50]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

In [ ]:
print(y_train)

In [ ]:
print(y_test)

## Feature Scaling

In [46]:
from sklearn.preprocessing import StandardScaler
#feature scaling only applied to logistic regression and neural networks not all 
# gradient dessent based algorithms
#applied only after training and test split data

sc = StandardScaler()
#fit:computes mean and standard deviations 
#transform: does standardisation using the mean and SD
X_train = sc.fit_transform(X_train)
#no need to compute mean and standard deviations again
#fit with old data
#hence only apply transform method
X_test = sc.transform(X_test)

In [48]:
print(X_train)

[[-0.77459667 -0.57735027  1.29099445 -0.19159184 -1.07812594]
 [-0.77459667  1.73205081 -0.77459667 -0.01411729 -0.07013168]
 [ 1.29099445 -0.57735027 -0.77459667  0.56670851  0.63356243]
 [-0.77459667 -0.57735027  1.29099445 -0.30453019 -0.30786617]
 [-0.77459667 -0.57735027  1.29099445 -1.90180114 -1.42046362]
 [ 1.29099445 -0.57735027 -0.77459667  1.14753431  1.23265336]
 [-0.77459667  1.73205081 -0.77459667  1.43794721  1.57499104]
 [ 1.29099445 -0.57735027 -0.77459667 -0.74014954 -0.56461943]]


In [ ]:
print(X_test)